// <auto-generated />
using System;
using FekraHubAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FekraHubAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118192436_PGdatabase")]
    partial class PGdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseEvent", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleID")
                        .HasColumnType("integer");

                    b.HasKey("EventID", "ScheduleID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("CourseEvent");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.AspNetPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("AspNetPermissions");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.AttendanceDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AttendanceDates");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.AttendanceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("AttendanceStatuses");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ContractPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConPage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolInfoId");

                    b.ToTable("contractPages");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Lessons")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.CourseAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceDateId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceDateId");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursesAttendances");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.CourseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("integer");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int?>("TypeID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("EventsTypes");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ExternalEmails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExternalEmails");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Studentid")
                        .HasColumnType("integer");

                    b.Property<byte[]>("file")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Studentid");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetNr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.MessageSender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MessageSenders");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.MessageSenderExternalEmail", b =>
                {
                    b.Property<int>("MessageSenderId")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalEmailId")
                        .HasColumnType("integer");

                    b.HasKey("MessageSenderId", "ExternalEmailId");

                    b.HasIndex("ExternalEmailId");

                    b.ToTable("MessageSenderExternalEmail");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.NotificationUser", b =>
                {
                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("NotificationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.PayRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("PayRoll");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Improved")
                        .HasColumnType("boolean");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.SchoolInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmailPortNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EmailServer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<string>("FromEmail")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PrivacyPolicy")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SchoolOwner")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrlDomain")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("SchoolInfos");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActiveStudent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("AdminApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int?>("CourseID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ParentApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentID")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("StreetNr")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("ParentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("StatusID");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentAttendances");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentID");

                    b.ToTable("StudentContract");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentsReportsKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Keys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolInfoId");

                    b.ToTable("studentsReportsKeys");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.TeacherAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseID")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusID")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherID")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeacherAttendances");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Tokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Token");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UploadTypeid")
                        .HasColumnType("integer");

                    b.Property<byte[]>("file")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("UploadTypeid");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.UploadType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UploadsType");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.UserMessage", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("MessageSenderId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "MessageSenderId");

                    b.HasIndex("MessageSenderId");

                    b.ToTable("UserMessage");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.WorkContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("File")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeacherID")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeacherID");

                    b.ToTable("WorkContracts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TeacherCourse", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherID")
                        .HasColumnType("text");

                    b.HasKey("CourseID", "TeacherID");

                    b.HasIndex("TeacherID");

                    b.ToTable("TeacherCourse");
                });

            modelBuilder.Entity("UploadCourse", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.Property<int>("UploadID")
                        .HasColumnType("integer");

                    b.HasKey("CourseID", "UploadID");

                    b.HasIndex("UploadID");

                    b.ToTable("UploadCourse");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("ActiveUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Birthplace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Graduation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUser")
                        .HasColumnType("text");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetNr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("CourseEvent", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.CourseSchedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ContractPage", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("ContractPages")
                        .HasForeignKey("SchoolInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Course", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Room", "Room")
                        .WithMany("Course")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.CourseAttendance", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.AttendanceDate", "AttendanceDate")
                        .WithMany("CourseAttendance")
                        .HasForeignKey("AttendanceDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.Course", "Course")
                        .WithMany("CourseAttendance")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttendanceDate");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.CourseSchedule", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", "Course")
                        .WithMany("CourseSchedule")
                        .HasForeignKey("CourseID");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Event", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.EventType", "EventType")
                        .WithMany("Event")
                        .HasForeignKey("TypeID");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Invoice", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Student", "Student")
                        .WithMany("Invoices")
                        .HasForeignKey("Studentid");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.MessageSenderExternalEmail", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.ExternalEmails", "ExternalEmail")
                        .WithMany("MessageSenderExternalEmails")
                        .HasForeignKey("ExternalEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.MessageSender", "MessageSender")
                        .WithMany("MessageSenderExternalEmails")
                        .HasForeignKey("MessageSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalEmail");

                    b.Navigation("MessageSender");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.NotificationUser", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Notifications", "Notifications")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "ApplicationUsers")
                        .WithMany("NotificationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUsers");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.PayRoll", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithMany("PayRoll")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Report", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Student", "Student")
                        .WithMany("Report")
                        .HasForeignKey("StudentId");

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithMany("Report")
                        .HasForeignKey("UserId");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Room", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Location", "Location")
                        .WithMany("room")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Student", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", "Course")
                        .WithMany("Student")
                        .HasForeignKey("CourseID");

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithMany("Student")
                        .HasForeignKey("ParentID");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentAttendance", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", "Course")
                        .WithMany("StudentAttendance")
                        .HasForeignKey("CourseID");

                    b.HasOne("FekraHubAPI.Data.Models.AttendanceStatus", "AttendanceStatus")
                        .WithMany("StudentAttendance")
                        .HasForeignKey("StatusID");

                    b.HasOne("FekraHubAPI.Data.Models.Student", "Student")
                        .WithMany("StudentAttendance")
                        .HasForeignKey("StudentID");

                    b.Navigation("AttendanceStatus");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentContract", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Student", "Student")
                        .WithMany("StudentContract")
                        .HasForeignKey("StudentID");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.StudentsReportsKey", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.SchoolInfo", "SchoolInfo")
                        .WithMany("StudentsReportsKeys")
                        .HasForeignKey("SchoolInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolInfo");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.TeacherAttendance", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", "Course")
                        .WithMany("TeacherAttendance")
                        .HasForeignKey("CourseID");

                    b.HasOne("FekraHubAPI.Data.Models.AttendanceStatus", "AttendanceStatus")
                        .WithMany("TeacherAttendance")
                        .HasForeignKey("StatusID");

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "Teacher")
                        .WithMany("TeacherAttendance")
                        .HasForeignKey("TeacherID");

                    b.Navigation("AttendanceStatus");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Tokens", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithOne("Token")
                        .HasForeignKey("FekraHubAPI.Data.Models.Tokens", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Upload", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.UploadType", "UploadType")
                        .WithMany("Upload")
                        .HasForeignKey("UploadTypeid");

                    b.Navigation("UploadType");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.UserMessage", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.MessageSender", "MessageSender")
                        .WithMany("UserMessages")
                        .HasForeignKey("MessageSenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithMany("UserMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageSender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.WorkContract", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", "User")
                        .WithMany("WorkContract")
                        .HasForeignKey("TeacherID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeacherCourse", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UploadCourse", b =>
                {
                    b.HasOne("FekraHubAPI.Data.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FekraHubAPI.Data.Models.Upload", null)
                        .WithMany()
                        .HasForeignKey("UploadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.AttendanceDate", b =>
                {
                    b.Navigation("CourseAttendance");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.AttendanceStatus", b =>
                {
                    b.Navigation("StudentAttendance");

                    b.Navigation("TeacherAttendance");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Course", b =>
                {
                    b.Navigation("CourseAttendance");

                    b.Navigation("CourseSchedule");

                    b.Navigation("Student");

                    b.Navigation("StudentAttendance");

                    b.Navigation("TeacherAttendance");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.EventType", b =>
                {
                    b.Navigation("Event");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ExternalEmails", b =>
                {
                    b.Navigation("MessageSenderExternalEmails");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Location", b =>
                {
                    b.Navigation("room");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.MessageSender", b =>
                {
                    b.Navigation("MessageSenderExternalEmails");

                    b.Navigation("UserMessages");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Notifications", b =>
                {
                    b.Navigation("NotificationUsers");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Room", b =>
                {
                    b.Navigation("Course");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.SchoolInfo", b =>
                {
                    b.Navigation("ContractPages");

                    b.Navigation("StudentsReportsKeys");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.Student", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Report");

                    b.Navigation("StudentAttendance");

                    b.Navigation("StudentContract");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.UploadType", b =>
                {
                    b.Navigation("Upload");
                });

            modelBuilder.Entity("FekraHubAPI.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("NotificationUsers");

                    b.Navigation("PayRoll");

                    b.Navigation("Report");

                    b.Navigation("Student");

                    b.Navigation("TeacherAttendance");

                    b.Navigation("Token")
                        .IsRequired();

                    b.Navigation("UserMessages");

                    b.Navigation("WorkContract");
                });
#pragma warning restore 612, 618
        }
    }
}
