version: '3.4'

services:
  webapi:
    image: fekra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__develpConn: "Server=sqlserver.railway.internal;Database=Fekra;User Id=sa;Password=SafeDocs_SqlServer_Docker_repo;TrustServerCertificate=True;Encrypt=True;"