version: '3.4'

services:
  webapi:
    image: fekra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__develpConn: "Server=db6561.public.databaseasp.net; Database=db6561; User Id=db6561; Password=Dq7?y#Y4X3+x; Encrypt=False; MultipleActiveResultSets=True;"

