version: '3.4'

services:
  webapi:
    image: fekra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__develpConn: "Server=db7844.public.databaseasp.net; Database=db7844; User Id=db7844; Password=o-4D=8BqTg2+; Encrypt=False; MultipleActiveResultSets=True;"