version: '3.8'  # Ensure you are using a valid version

services:
  webapi:
    image: fekrahubapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"  # Change the host port to 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "FekraHub2024-nw"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
