version: '3.4'

services:
  webapi:
    image: fekra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__develpConn: "Server=db6561.public.databaseasp.net,1433; Database=db6561; User Id=db6561; Password=Dq7?y#Y4X3+x; Encrypt=False; MultipleActiveResultSets=True;"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "FekraHubApi-NW"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:

